apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tradiecore-public-documentation
  description: Catalog entities for tradiecore-public-documentation.
spec:
  targets:
    - ./catalog/**/*.yaml
